from __future__ import annotations

import argparse
from pathlib import Path

EXCLUDED_DIR_NAMES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".idea",
    "build",
    "dist",
    ".eggs",
}

TREE_ROOTS = (
    "src/ai_assistant",
    "tests",
    "docs",
    "context",
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _is_excluded(path: Path) -> bool:
    return any(part in EXCLUDED_DIR_NAMES for part in path.parts)


def _iter_tree_lines(root: Path, max_depth: int = 3, max_entries_per_dir: int = 60) -> list[str]:
    lines: list[str] = []

    def walk(path: Path, prefix: str, depth: int) -> None:
        if depth > max_depth or _is_excluded(path):
            return
        if not path.exists():
            return
        entries = [item for item in path.iterdir() if not _is_excluded(item)]
        entries.sort(key=lambda item: (not item.is_dir(), item.name.lower()))

        if len(entries) > max_entries_per_dir:
            visible = entries[:max_entries_per_dir]
            hidden_count = len(entries) - len(visible)
        else:
            visible = entries
            hidden_count = 0

        for index, entry in enumerate(visible):
            connector = "└── " if index == len(visible) - 1 and hidden_count == 0 else "├── "
            lines.append(f"{prefix}{connector}{entry.name}")
            if entry.is_dir():
                extension = "    " if connector == "└── " else "│   "
                walk(entry, prefix + extension, depth + 1)

        if hidden_count > 0:
            lines.append(f"{prefix}└── ... ({hidden_count} more entries)")

    lines.append(root.name)
    walk(root, "", 0)
    return lines


def _collect_python_file_sizes(base: Path) -> list[tuple[Path, int]]:
    results: list[tuple[Path, int]] = []
    if not base.exists():
        return results
    for file_path in base.rglob("*.py"):
        if _is_excluded(file_path):
            continue
        try:
            line_count = sum(1 for _ in file_path.open("r", encoding="utf-8"))
        except OSError:
            continue
        results.append((file_path, line_count))
    results.sort(key=lambda item: item[1], reverse=True)
    return results


def _build_project_map(root: Path) -> str:
    tree_blocks: list[str] = []
    for relative in TREE_ROOTS:
        absolute = root / relative
        if not absolute.exists():
            continue
        tree_lines = _iter_tree_lines(absolute)
        tree_blocks.append(f"### `{relative}`\n\n```text\n" + "\n".join(tree_lines) + "\n```")

    src_sizes = _collect_python_file_sizes(root / "src")
    tests_sizes = _collect_python_file_sizes(root / "tests")

    top_src = src_sizes[:15]
    top_tests = tests_sizes[:10]

    top_src_lines = "\n".join(
        f"- `{path.relative_to(root)}`: {lines} lines" for path, lines in top_src
    ) or "- (no python files)"
    top_tests_lines = "\n".join(
        f"- `{path.relative_to(root)}`: {lines} lines" for path, lines in top_tests
    ) or "- (no python files)"

    return "\n".join(
        [
            "# Project Map (Auto-generated)",
            "",
            "_Generated by `python -m ai_assistant.devtools.sync_docs`._",
            "",
            "## Scope and Exclusions",
            "",
            "- Scanned roots: `src/ai_assistant`, `tests`, `docs`, `context`.",
            "- Excluded from scan by design: `.venv`, `.git`, `__pycache__`, `.pytest_cache`, `.mypy_cache`, `.ruff_cache`, `.idea`, build artifacts.",
            "- Reason: avoid expensive and noisy indexing of environment/dependency files.",
            "",
            "## Entry Points",
            "",
            "- `main.py` -> loads settings and starts channel module.",
            "- `src/ai_assistant/app.py` -> application startup.",
            "- `src/ai_assistant/bootstrap.py` -> composition root and dependency wiring.",
            "",
            "## Tree",
            "",
            "\n\n".join(tree_blocks),
            "",
            "## Largest Python Files in `src`",
            "",
            top_src_lines,
            "",
            "## Largest Python Files in `tests`",
            "",
            top_tests_lines,
            "",
            "## Notes for LLM Agents",
            "",
            "- Prefer reading `docs/CODEX_START.md` first.",
            "- Use `python -m ai_assistant.devtools.sync_docs` after structural edits.",
            "- Keep documentation and generated context files in sync before finishing a task.",
            "",
        ]
    )


def _build_codex_context(root: Path) -> str:
    return "\n".join(
        [
            "# Codex Context (Auto-generated)",
            "",
            "_Generated by `python -m ai_assistant.devtools.sync_docs`._",
            "",
            "## Read First",
            "",
            "- `docs/CODEX_START.md`",
            "- `docs/ARCHITECTURE.md`",
            "- `docs/DEVELOPMENT_GUIDELINES.md`",
            "- `docs/PROJECT_MAP.md`",
            "",
            "## Project Purpose",
            "",
            "- Modular home AI assistant with pluggable channels, LLM providers, settings backends, and permissions.",
            "",
            "## Critical Scan Rule",
            "",
            "- Do not perform full-repo deep scans through `.venv`.",
            "- Exclude: `.venv`, `.git`, `__pycache__`, `.pytest_cache`, `.mypy_cache`, `.ruff_cache`, `.idea`.",
            "",
            "## Sync Command",
            "",
            "- `python -m ai_assistant.devtools.sync_docs`",
            "- Check mode: `python -m ai_assistant.devtools.sync_docs --check`",
            "",
            "## Repo Paths",
            "",
            f"- Root: `{root}`",
            "- Main code: `src/ai_assistant/`",
            "- Tests: `tests/`",
            "- Context docs: `context/`",
            "",
        ]
    )


def _sync_file(path: Path, new_content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    normalized_new = new_content.rstrip() + "\n"
    normalized_existing = existing.rstrip() + ("\n" if existing else "")
    changed = normalized_existing != normalized_new
    if changed and not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized_new, encoding="utf-8")
    return changed


def run(check: bool = False) -> int:
    root = _repo_root()
    project_map_path = root / "docs" / "PROJECT_MAP.md"
    codex_context_path = root / "context" / "CODEX_CONTEXT.md"

    changed_project_map = _sync_file(project_map_path, _build_project_map(root), check=check)
    changed_codex_context = _sync_file(codex_context_path, _build_codex_context(root), check=check)

    changed = changed_project_map or changed_codex_context
    if check and changed:
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync generated project documentation.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Return non-zero if generated docs are out of date.",
    )
    args = parser.parse_args()
    return run(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
